### ISSUE TITLE
Mistake in computation

### ISSUE THREAD

**Issue by thinhong** [OUCRU-Modelling/eva#4]
https://github.com/OUCRU-Modelling/eva/blob/0593656d5c4343554a6b5cecb173c925912e6a98/vac_cov.qmd#L58-L75

You need to use `date_m1` and `date_m2` instead of `is_m1`/`is_m2`. `is_m1` is whether the child was vaccinated during the follow-up period. For example, you compute the coverage in Sep 2022 but they were vaccinated in Dec 2022, if you use `is_m1` they are still counted as vaccinated. So the correct way to do this is:

```
# date_compute is the date we compute coverage
date_compute <- ymd("2022-09-01")

df |>
  mutate(
    # Compute age on this date_compute
    age = decimal_date(date_compute) - decimal_date(dob),
    # If the vaccination date is before this date_compute, they are counted as vaccinated
    # You can also use date_compute - 2 weeks here (but maybe then you have to subset with age + 2 weeks?), let try both and we discuss later
    is_m2 = if_else(date_m2 <= date_compute, 1, 0)
  ) |>
  # Subset children >= 12 month-old (or 1 year-old) since we are looking at the 2nd dose
  filter(age >= 1, age <= 5) |> 
  summarise(m2 = sum(is_m2, na.rm = T), n = n(), cov = m2/n)
```

Do similar to `date_m1` for children >= 9 month-old.

Also remember to clean the incorrect `date_m1` and `date_m2`. I saw some `date_m1` < 1900 and `date_m2` > 2100.

**Comment by pntnguyen** [comment]
Fixed
